### ISSUE TITLE
Vue Language Service crashed

### ISSUE THREAD

**Issue by panxiuqing** [octref/vetur#123]
Vue language service closed when I update vetur to 0.6

![image](https://cloud.githubusercontent.com/assets/476617/25209042/f4a465c0-25aa-11e7-810a-ca4f4906f61a.png)

My settings:

![image](https://cloud.githubusercontent.com/assets/476617/25209102/57ec77b2-25ab-11e7-97c0-8093cec5b10a.png)

**Comment by octref** [comment]
Do you happen to have a `jsconfig` or `tsconfig` in your project? If so can you paste its content?

**Comment by dracher** [comment]
same issue after upgrade to 0.6.0, but different output
```
TypeError: Cannot read property 'get' of undefined
    at isNameOfExportsOrModuleExportsAliasDeclaration (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:23318:46)
    at bindStaticPropertyAssignment (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:23396:17)
    at bindWorker (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:23079:29)
    at bind (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:22974:13)
    at bindConditionalExpressionFlow (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:22441:13)
    at bindChildrenWorker (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:21837:21)
    at bindChildren (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:21746:17)
    at bind (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:22985:21)
    at visitNode (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:14662:20)
    at Object.forEachChild (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:14725:21)
[Info  - 9:44:57 AM] Connection to server got closed. Server will restart.
/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:23318
                var symbol = container.locals.get(node.text);
                                             ^

TypeError: Cannot read property 'get' of undefined
    at isNameOfExportsOrModuleExportsAliasDeclaration (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:23318:46)
    at bindStaticPropertyAssignment (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:23396:17)
    at bindWorker (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:23079:29)
    at bind (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:22974:13)
    at bindConditionalExpressionFlow (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:22441:13)
    at bindChildrenWorker (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:21837:21)
    at bindChildren (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:21746:17)
    at bind (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:22985:21)
    at visitNode (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:14662:20)
    at Object.forEachChild (/home/dracher/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:14725:21)
[Error - 9:45:01 AM] Connection to server got closed. Server will not be restarted.
```
ENV:
- Fedora 25
- VsCode Version 1.11.2
- Vuetur 0.6.0

**Comment by The-Smallest** [comment]
Same problem.

Here some logs from extension:
```
C:\Users\Ivan\.vscode\extensions\octref.vetur-0.6.0\client\server\node_modules\vetur-vls\lib\parser\htmlScanner.js:46
            this.len = source.length;
                             ^
TypeError: Cannot read property 'length' of undefined
    at new MultiLineStream (C:\Users\Ivan\.vscode\extensions\octref.vetur-0.6.0\client\server\node_modules\vetur-vls\lib\parser\htmlScanner.js:46:30)
    at Object.createScanner (C:\Users\Ivan\.vscode\extensions\octref.vetur-0.6.0\client\server\node_modules\vetur-vls\lib\parser\htmlScanner.js:188:22)
    at Object.getDocumentRegions (C:\Users\Ivan\.vscode\extensions\octref.vetur-0.6.0\client\server\modes\embeddedSupport.js:9:35)
    at C:\Users\Ivan\.vscode\extensions\octref.vetur-0.6.0\client\server\modes\languageModes.js:11:125
    at Object.get (C:\Users\Ivan\.vscode\extensions\octref.vetur-0.6.0\client\server\languageModelCache.js:30:33)
    at C:\Users\Ivan\.vscode\extensions\octref.vetur-0.6.0\client\server\modes\javascriptMode.js:14:43
    at Object.get (C:\Users\Ivan\.vscode\extensions\octref.vetur-0.6.0\client\server\languageModelCache.js:30:33)
    at C:\Users\Ivan\.vscode\extensions\octref.vetur-0.6.0\client\server\modes\javascriptMode.js:88:37
    at Array.map (native)
    at Object.resolveModuleNames (C:\Users\Ivan\.vscode\extensions\octref.vetur-0.6.0\client\server\modes\javascriptMode.js:80:32)
[Error - 4:49:14] Connection to server got closed. Server will not be restarted.
````

Extra information:
- No _jsconfig_ or _tsconfig_.
- Error doesn't reproduce if I create fresh project with `vue init webpack-simple` 
- I use *pug* in templates
- OS: Windows 10

**Comment by jing2si** [comment]
Same problem as @The-Smallest .

**Comment by octref** [comment]
For people having problems -- it would be great if you can find a sample project like vue-hackernews-2, or some vue-templates and still make vetur crash.

Basically I need a project where I could repro the problem and the bug can be easily resolved.

**Comment by The-Smallest** [comment]
Here some extra information: function _getDocumentRegions_ (embeddedSupport.js:11:35) really gets strange input object for parameter `document`:

```
FullTextDocument {
  _uri: 'file:///s%3A/Projects/myproject/dist/%21%21../node_modules/css-loader/index.js%21../node_modules/vue-loader/lib/style-compiler/index.js%3F%7B%22id%22%3A%22data-v-01ba4bac%22%2C%22scoped%22%3Afalse%2C%22hasInlineConfig%22%3Afalse%7D%21../node_modules/sass-loader/lib/loader.js%21../node_modules/vue-loader/lib/selector.js%3Ftype%3Dstyles%26index%3D0%21./Footer.vue',
  _languageId: 'vue',
  _version: 0,
  _content: undefined,
  _lineOffsets: null }
```

**Comment by soundtina** [comment]
i also meet the vls crashed problem

**Comment by The-Smallest** [comment]
I found way to reproduce error on _webpack-simple_ template:
Simply write *bad import* in _script_ section. Example:
```
import Something from './PathThatDoesnotExists.vue'
```

Hope that helps.

**Comment by FlynnLeeGit** [comment]
here's what i got
/Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46
            this.len = source.length;
                             ^

TypeError: Cannot read property 'length' of undefined
    at new MultiLineStream (/Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46:30)
    at Object.createScanner (/Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:188:22)
    at Object.getDocumentRegions (/Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/embeddedSupport.js:9:35)
    at /Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/languageModes.js:11:125
    at Object.get (/Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/languageModelCache.js:30:33)
    at /Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/javascriptMode.js:14:43
    at Object.get (/Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/languageModelCache.js:30:33)
    at /Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/javascriptMode.js:88:37
    at Array.map (native)
    at Object.resolveModuleNames (/Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/javascriptMode.js:80:32)
[Info  - 10:40:14 AM] Connection to server got closed. Server will restart.
/Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46
            this.len = source.length;

**Comment by octref** [comment]
@The-Smallest 

That's it -- Thanks!

**Comment by yswnldy** [comment]
Same problem as @The-Smallest .

**Comment by exonuclease** [comment]
Same problem as @The-Smallest .
Fedora 25
VsCode Version 1.11.2
Vuetur 0.6.0
/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46
            this.len = source.length;
                             ^

TypeError: Cannot read property 'length' of undefined
    at new MultiLineStream (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46:30)
    at Object.createScanner (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:188:22)
    at Object.getDocumentRegions (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/embeddedSupport.js:9:35)
    at /home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/languageModes.js:11:125
    at Object.get (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/languageModelCache.js:30:33)
    at /home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/javascriptMode.js:14:43
    at Object.get (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/languageModelCache.js:30:33)
    at /home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/javascriptMode.js:88:37
    at Array.map (native)
    at Object.resolveModuleNames (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/javascriptMode.js:80:32)
[Info  - 下午2:10:59] Connection to server got closed. Server will restart.
/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46
            this.len = source.length;
                             ^

TypeError: Cannot read property 'length' of undefined
    at new MultiLineStream (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46:30)
    at Object.createScanner (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:188:22)
    at Object.getDocumentRegions (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/embeddedSupport.js:9:35)
    at /home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/languageModes.js:11:125
    at Object.get (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/languageModelCache.js:30:33)
    at /home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/javascriptMode.js:14:43
    at Object.get (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/languageModelCache.js:30:33)
    at /home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/javascriptMode.js:88:37
    at Array.map (native)
    at Object.resolveModuleNames (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/javascriptMode.js:80:32)
[Info  - 下午2:11:15] Connection to server got closed. Server will restart.
/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46
            this.len = source.length;
                             ^

TypeError: Cannot read property 'length' of undefined
    at new MultiLineStream (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46:30)
    at Object.createScanner (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:188:22)
    at Object.getDocumentRegions (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/embeddedSupport.js:9:35)
    at /home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/languageModes.js:11:125
    at Object.get (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/languageModelCache.js:30:33)
    at /home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/javascriptMode.js:14:43
    at Object.get (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/languageModelCache.js:30:33)
    at /home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/javascriptMode.js:88:37
    at Array.map (native)
    at Object.resolveModuleNames (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/javascriptMode.js:80:32)
[Error - 下午2:11:31] Connection to server got closed. Server will not be restarted.

**Comment by panxiuqing** [comment]
@octref @The-Smallest 
The file exists at that path and every file.vue cause the crash
My tsconfig.json : 
```json
{
    // 请访问 https://go.microsoft.com/fwlink/?LinkId=759670
    // 参阅有关 jsconfig.json 格式的文档
    "compilerOptions": {
        "target": "ES5",
        "module": "es2015",
        "moduleResolution": "node",
        "allowSyntheticDefaultImports": true
    },
    "exclude": [
        "node_modules",
        "bower_components",
        "jspm_packages",
        "tmp",
        "temp"
    ],
    "files": [
        "./Lib/Collections.ts",
        "./Lib/EventDispatcher.ts",
        "./Lib/ShapeGenerator.ts",
        "./Lib/Constant.ts",
        "./Lib/Util.ts",
        "WhiteBoardClient.ts"
    ]
}
```

**Comment by askz** [comment]
Hi, different error here : 
```
/home/xxxxx/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:10566
            throw new Error("start < 0");
            ^

Error: start < 0
    at createTextSpan (/home/xxxxx/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:10566:19)
    at Object.createTextSpanFromBounds (/home/xxxxx/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:10575:16)
    at getErrorSpanForNode (/home/xxxxx/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:7075:19)
    at createDiagnosticForNodeInSourceFile (/home/xxxxx/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:6999:20)
    at Object.createDiagnosticForNode (/home/xxxxx/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:6995:16)
    at /home/xxxxx/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:21582:58
    at Object.forEach (/home/xxxxx/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:1423:30)
    at declareSymbol (/home/xxxxx/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:21581:28)
    at declareModuleMember (/home/xxxxx/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:21600:28)
    at declareSourceFileMember (/home/xxxxx/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:22646:19)
    at declareSymbolAndAddToSymbolTableWorker (/home/xxxxx/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/typescript/lib/typescript.js:22596:28)
[Info  - 11:24:17 AM] Connection to server got closed. Server will restart.
```

**Comment by BelinChung** [comment]
```
[Error - 5:32:59 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'parameters' of undefined
  Code: -32603 
[Error - 5:33:06 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'parameters' of undefined
  Code: -32603 
```
`Vue language server` crashed after upgrade `vetur` to 0.6.0

**Comment by Rocket1184** [comment]
@askz I use ArchLinux too and have the same issue

**Comment by octref** [comment]
`TypeError: Cannot read property 'length' of undefined` should be fixed with 0.6.1.

For people having other problems @askz, @BelinChung and @dracher, give 0.6.1 a try and open another issue if the problem still persists.

**Comment by panxiuqing** [comment]
@octref 
Update to 0.6.1 doesn't resolve my error , but I find something maybe helpful : 
when a project initialized by npm has a sub folder also initialized by npm , open somefile.vue in the sub folder will cause the error , otherwise not

**Comment by soundtina** [comment]
@panxiuqing  that's the problem!
my project is node web app like this

-- app
----package.json
----service
----static
------bac.vue
------package.json

**when i open static folder in vscode works fine
but when i open App , vls crashed.**

**Comment by octref** [comment]
@panxiuqing @soundtina I can't repro it. Can you make a small repo that demonstrates the problem and upload it to GitHub so I can debug?

**Comment by mattiasholmqvist** [comment]
I have the same issue as @askz after upgrading to 0.6.1 (on Mac).

`Error: start < 0
    at createTextSpan (/Users/mattias/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10566:19)
    at Object.createTextSpanFromBounds (/Users/mattias/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10575:16)
    at getErrorSpanForNode (/Users/mattias/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:7075:19)
    at createDiagnosticForNodeInSourceFile (/Users/mattias/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6999:20)
    at Object.createDiagnosticForNode (/Users/mattias/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6995:16)
    at /Users/mattias/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21582:58
    at Object.forEach (/Users/mattias/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:1423:30)
    at declareSymbol (/Users/mattias/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21581:28)
    at declareModuleMember (/Users/mattias/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21600:28)
    at declareSourceFileMember (/Users/mattias/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:22646:19)
[Info  - 8:53:19 PM] Connection to server got closed. Server will restart.`

**Comment by mattiasholmqvist** [comment]
Thanks for pushing 0.6.2! It fixed my crash issue.

**Comment by danikane** [comment]
Getting this at 0.6.4:
```
C:\Users\dindin\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:23038
        function bindWorker(node) {
                           ^

RangeError: Maximum call stack size exceeded
    at bindWorker (C:\Users\dindin\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:23038:28)
    at bind (C:\Users\dindin\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:22974:13)
    at visitNode (C:\Users\dindin\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:14662:20)
    at Object.forEachChild (C:\Users\dindin\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:14826:24)
    at bindEachChild (C:\Users\dindin\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:21771:16)
    at bindBinaryExpressionFlow (C:\Users\dindin\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:22416:17)
    at bindChildrenWorker (C:\Users\dindin\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:21831:21)
    at bindChildren (C:\Users\dindin\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:21746:17)
    at bind (C:\Users\dindin\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:22985:21)
    at visitNode (C:\Users\dindin\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:14662:20)
[Info  - 23:16:16] Connection to server got closed. Server will restart.
```

**Comment by octref** [comment]
@danikane https://github.com/octref/vetur/issues/166#issuecomment-298330152

**Comment by danikane** [comment]
Thanks, will try! :)
