### ISSUE TITLE
also have the vue language server crashed

### ISSUE THREAD

**Issue by FlynnLeeGit** [octref/vetur#124]
/Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46
            this.len = source.length;
                             ^

TypeError: Cannot read property 'length' of undefined
    at new MultiLineStream (/Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46:30)
    at Object.createScanner (/Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:188:22)
    at Object.getDocumentRegions (/Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/embeddedSupport.js:9:35)
    at /Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/languageModes.js:11:125
    at Object.get (/Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/languageModelCache.js:30:33)
    at /Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/javascriptMode.js:14:43
    at Object.get (/Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/languageModelCache.js:30:33)
    at /Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/javascriptMode.js:88:37
    at Array.map (native)
    at Object.resolveModuleNames (/Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/modes/javascriptMode.js:80:32)
[Info  - 10:40:14 AM] Connection to server got closed. Server will restart.
/Users/sfdd/.vscode/extensions/octref.vetur-0.6.0/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46
            this.len = source.length;

**Comment by rjoo** [comment]
How did you fix this?
