### ISSUE TITLE
Server still crash on 0.6.1 - throw new Error("start < 0");

### ISSUE THREAD

**Issue by askz** [octref/vetur#128]
Still having issue with server, last VSCode version on ArchLinux updated with node v7.8.0
```
/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10566
            throw new Error("start < 0");
            ^

Error: start < 0
    at createTextSpan (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10566:19)
    at Object.createTextSpanFromBounds (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:10575:16)
    at getErrorSpanForNode (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:7075:19)
    at createDiagnosticForNodeInSourceFile (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6999:20)
    at Object.createDiagnosticForNode (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:6995:16)
    at /home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21582:58
    at Object.forEach (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:1423:30)
    at declareSymbol (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21581:28)
    at declareModuleMember (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:21600:28)
    at declareSourceFileMember (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:22646:19)
    at declareSymbolAndAddToSymbolTableWorker (/home/xxxxxx/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:22596:28)
[Error - 7:43:37 PM] Connection to server got closed. Server will not be restarted.

```

**Comment by octref** [comment]
Can you help me finding a repro? Try it on some public vue projects like https://github.com/vuejs/vue-hackernews-2.0 or https://github.com/vuejs-templates/webpack and see if the server crashes? If not, can you try to put some code from your codebase to a template project and manage to crash vetur's Language Server?

This is what @The-Smallest did and was extremely helpful for me to fix the previous crash:

![image](https://cloud.githubusercontent.com/assets/4033249/25244845/4e001da6-25d0-11e7-9d5a-6a3d9f8ec3a8.png)

**Comment by rafaelpimpa** [comment]
It's crashing for me too, let me see if I can reproduce.

**Comment by stoked74** [comment]
It's happening to me as well. I just created a stock asp.net core web api project using the yeoman generator and as soon as I opened the project it it started crashing.

npm install -g yo bower
npm install -g generator-aspnet@0.2.6
yo aspnet

**Comment by jing2si** [comment]
```
C:\Users\Michael\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:10566
            throw new Error("start < 0");
            ^

Error: start < 0
    at createTextSpan (C:\Users\Michael\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:10566:19)
    at Object.createTextSpanFromBounds (C:\Users\Michael\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:10575:16)
    at getErrorSpanForNode (C:\Users\Michael\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:7075:19)
    at createDiagnosticForNodeInSourceFile (C:\Users\Michael\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:6999:20)
    at Object.createDiagnosticForNode (C:\Users\Michael\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:6995:16)
    at C:\Users\Michael\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:21582:58
    at Object.forEach (C:\Users\Michael\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:1423:30)
    at declareSymbol (C:\Users\Michael\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:21581:28)
    at declareModuleMember (C:\Users\Michael\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:21600:28)
    at declareSourceFileMember (C:\Users\Michael\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:22646:19)
[Info  - 上午10:47:03] Connection to server got closed. Server will restart.
C:\Users\Michael\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:10566
            throw new Error("start < 0");
```

**Comment by jing2si** [comment]
I find the crashed reason.
If in a vue file script tag write `import Vue`, that will cause crash.
write`import vue` do not cause crash.
![reason](https://cloud.githubusercontent.com/assets/2288824/25263791/a7f72a60-2694-11e7-93c0-9bedee264cb9.gif)

**Comment by octref** [comment]
@jing2si 

Thanks! I'm able to repro it. Will look into a fix soon.

**Comment by sandersn** [comment]
It's because vetur 0.6 inserts a hidden `import Vue from 'vue'` for you. I forgot that people might still want to write it explicitly. In that case, it should not insert a hidden one.

**Comment by octref** [comment]
@jing2si Thanks for the repro.

For people having this problem, 0.6.2 is published with @sandersn's fix. Please give it a try.
@jing2si's case is resolved by 0.6.2 at least.

**Comment by ronjouch** [comment]
0.6.2 fixed it for me too, thanks! 👍

**Comment by cynecx** [comment]
It seems to be fixed but I am experiencing abnormal performance issues. For example, if auto-complete is triggered it shows a loading sign which stays for some seconds until the auto-complete dialog shows up. Is anyone else experiencing this?

Also is it normal that the vetur server process uses like 1-2GiB ram?

**Comment by octref** [comment]
@cynecx That's not normal. I'm looking into that in #131.
