### ISSUE TITLE
After upgrading to version 0.6.1 the vue server crashes

### ISSUE THREAD

**Issue by fishke** [octref/vetur#129]
I am using Windows 10, and VSCode 1.11.2.

I've upgraded to the latest version (0.6.1) and now i get this error:

> TypeError: Cannot read property 'get' of undefined
    at isNameOfExportsOrModuleExportsAliasDeclaration (C:\Users\tomer\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:23318:46)
    at bindStaticPropertyAssignment (C:\Users\tomer\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:23396:17)
    at bindWorker (C:\Users\tomer\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:23079:29)
    at bind (C:\Users\tomer\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:22974:13)
    at bindConditionalExpressionFlow (C:\Users\tomer\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:22441:13)
    at bindChildrenWorker (C:\Users\tomer\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:21837:21)
    at bindChildren (C:\Users\tomer\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:21746:17)
    at bind (C:\Users\tomer\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:22985:21)
    at visitNode (C:\Users\tomer\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:14662:20)
    at Object.forEachChild (C:\Users\tomer\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:14725:21)
[Error - 21:32:51] Connection to server got closed. Server will not be restarted.

**Comment by octref** [comment]
#127
