### ISSUE TITLE
server still crashed on 0.6.1 CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by exonuclease** [octref/vetur#131]
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/share/code/libnode.so]
 2: 0x7f23b86632a7 [/usr/share/code/libnode.so]
 3: v8::Utils::ApiCheck(bool, char const*, char const*) [/usr/share/code/libnode.so]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/share/code/libnode.so]
 5: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/share/code/libnode.so]
 6: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/share/code/libnode.so]
 7: 0x3768afe08206
[Info  - 上午8:27:56] Connection to server got closed. Server will restart.
Fedora25
vscode 1.11.2

**Comment by soundtina** [comment]
still creshed!

> [0421/092928:ERROR:tcp_listen_socket.cc(76)] Could not bind socket to 127.0.0.1:6005
> [0421/092928:ERROR:node_debugger.cc(86)] Cannot start debugger server

**Comment by byends** [comment]
+1024

**Comment by byends** [comment]
> workbench.main.js:29 Connection is closed.: Error: Connection is closed.
    at ConnectionError.Error (native)
    at new ConnectionError (C:\Users\BYENDS\.vscode\extensions\octref.vetur-0.6.1\client\node_modules\vscode-jsonrpc\lib\main.js:116:28)
    at throwIfClosedOrDisposed (C:\Users\BYENDS\.vscode\extensions\octref.vetur-0.6.1\client\node_modules\vscode-jsonrpc\lib\main.js:481:19)
    at Object.sendNotification (C:\Users\BYENDS\.vscode\extensions\octref.vetur-0.6.1\client\node_modules\vscode-jsonrpc\lib\main.js:522:13)
    at C:\Users\BYENDS\.vscode\extensions\octref.vetur-0.6.1\client\node_modules\vscode-jsonrpc\lib\main.js:627:32
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:16423)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:20054)
    at e.cancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:22821)
    at e.cancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:23431)
    at ._oncancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:58954)
    at _cancelAction (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:55158)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:50915)
    at _run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:53226)
    at cancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:52391)
    at _cancelAction (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:53474)
    at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:50915)e.onUnexpectedError @ workbench.main.js:29
workbench.main.js:29 [Extension Host] rejected promise not handled within 1 second

**Comment by byends** [comment]
I can't coding continue.. pls fix it

**Comment by vv13** [comment]
still crashed. need your help!

**Comment by soundtina** [comment]
just open the **static** folder, don't open the folder that both contain **satic** and **node_modules**

**Comment by minororange** [comment]
+10086 i need your help @octref

**Comment by mgesmundo** [comment]
@octref please fix this!

**Comment by askz** [comment]
@mgesmundo please be nice

**Comment by octref** [comment]
Was able to repro. Looking into it...

**Comment by octref** [comment]
Can people having problem try this:

- Create a `tsconfig.json` or `jsconfig.json` file in your project root
- Put this in it

```json
{
  "exclude": [
    "node_modules"
  ]
}
```

Does your project still crash?

**Comment by exonuclease** [comment]
@octref I have created jsconfig.json and  still crash

**Comment by octref** [comment]
@exonuclease How large is your project?
Do you have any sub-project that also has `node_modules` in it?

**Comment by exonuclease** [comment]
@octref Umm...more than ten .vue files not very large
No and i also add files.exclude to my settings.json it still doesn't work

**Comment by octref** [comment]
@exonuclease 
Is your project secret or do you mind sharing with me?

**Comment by exonuclease** [comment]
@octref sorry it is secret.
I will try to find an open resource project that can cause this

**Comment by octref** [comment]
@exonuclease That'd help a lot, thanks!

**Comment by exonuclease** [comment]
@octref this project https://github.com/mrgodhani/rss-reader
run npm install and open .vue file it caused another error...
/home/guoyifan/.vscode/extensions/octref.vetur-0.6.3/client/server/node_modules/typescript/lib/typescript.js:23318
                var symbol = container.locals.get(node.text);
                                             ^

TypeError: Cannot read property 'get' of undefined
    at isNameOfExportsOrModuleExportsAliasDeclaration (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.3/client/server/node_modules/typescript/lib/typescript.js:23318:46)
    at bindStaticPropertyAssignment (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.3/client/server/node_modules/typescript/lib/typescript.js:23396:17)
    at bindWorker (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.3/client/server/node_modules/typescript/lib/typescript.js:23079:29)
    at bind (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.3/client/server/node_modules/typescript/lib/typescript.js:22974:13)
    at visitNode (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.3/client/server/node_modules/typescript/lib/typescript.js:14662:20)
    at Object.forEachChild (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.3/client/server/node_modules/typescript/lib/typescript.js:14826:24)
    at bindEachChild (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.3/client/server/node_modules/typescript/lib/typescript.js:21771:16)
    at bindBinaryExpressionFlow (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.3/client/server/node_modules/typescript/lib/typescript.js:22416:17)
    at bindChildrenWorker (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.3/client/server/node_modules/typescript/lib/typescript.js:21831:21)
    at bindChildren (/home/guoyifan/.vscode/extensions/octref.vetur-0.6.3/client/server/node_modules/typescript/lib/typescript.js:21746:17)
[Info  - 上午10:05:33] Connection to server got closed. Server will restart.
/home/guoyifan/.vscode/extensions/octref.vetur-0.6.3/client/server/node_modules/typescript/lib/typescript.js:23318
                var symbol = container.locals.get(node.text);
                                             ^

**Comment by octref** [comment]
The problem is you have `app/node_modules` which gets module resolved...
But now vetur should handle `node_modules` even if it's not in top directory.
Wait for 0.6.4.
