### ISSUE TITLE
Possible error in dependency 'vscode-jsonrpc'

### ISSUE THREAD

**Issue by jonthegiant** [octref/vetur#137]
Not entirely sure this is the fault of vetur, so apologies if it turns out not to be.
This error is thrown randomly after loading the repo, and or reloading the workbench. 

Unfortunately I can't include a reproducible case because the repo is a large internal project.

**No other Vue extensions are installed.**
```
[15792:0421/171353:INFO:CONSOLE(29)] "Connection is closed.: Error: Connection is closed.
    at ConnectionError.Error (native)
    at new ConnectionError (C:\Users\XXXXXX\.vscode\extensions\octref.vetur-0.6.1\client\node_modules\vscode-jsonrpc\lib\main.js:116:28)
    at throwIfClosedOrDisposed (C:\Users\XXXXXX\.vscode\extensions\octref.vetur-0.6.1\client\node_modules\vscode-jsonrpc\lib\main.js:481:19)
    at Object.sendNotification (C:\Users\XXXXXX\.vscode\extensions\octref.vetur-0.6.1\client\node_modules\vscode-jsonrpc\lib\main.js:522:13)
    at C:\Users\XXXXXX\.vscode\extensions\octref.vetur-0.6.1\client\node_modules\vscode-jsonrpc\lib\main.js:627:32
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:16423)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:20054)
    at e.cancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:22821)
    at e.cancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:23431)
    at ._oncancel (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:58954)", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js
(29)
```

Followed by...
```[15792:0421/171618:INFO:CONSOLE(5)] "[uncaught exception]: Error: write EPIPE", source: file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[15792:0421/171618:INFO:CONSOLE(5)] "Error: write EPIPE
    at exports._errnoException (util.js:1026:11)
    at Socket._writeGeneric (net.js:706:26)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at clearBuffer (_stream_writable.js:414:7)
    at onwrite (_stream_writable.js:346:7)
    at Socket.WritableState.onwrite (_stream_writable.js:89:5)
    at WriteWrap.afterWrite (net.js:807:12)", source: file:///C:/Program%20Files%20(x86)/Microsoft%20VS%20Code/resources/app/out/vs/workbench/electron-browser/bootstrap/index.js (5)
[15792:0421/171618:INFO:CONSOLE(160)] "Uncaught Error: write EPIPE", source: events.js (160)
[15792:0421/171618:INFO:CONSOLE(28)] "Extension host terminated unexpectedly. Please reload the window to recover.", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (28)
[15792:0421/171618:INFO:CONSOLE(29)] "Extension host terminated unexpectedly. Code: ", source: file:///C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/electron-browser/workbench.main.js (29)
```

![image](https://cloud.githubusercontent.com/assets/5591930/25287424/d7da80e6-2686-11e7-933f-83629cc4bfba.png)

**Comment by octref** [comment]
If there is no repro case there isn't much I can do...

Does this happen immediately after you load the project, or is it after a while (if that's the case it might have something to do with the module resolution)?

I'll keep an eye while working on Vue projects with vetur to see if this happens to me.

**Comment by jonthegiant** [comment]
Understandable. To answer your question it happens ~2-5minutes after loading & opening the project folder in VS Code.

**Comment by octref** [comment]
We'll improve the module resolution as it's also causing #131. I'll ping you back once we update the module resolution.

**Comment by octref** [comment]
Try 0.6.4 with updated module resolution and see if it's resolved.

Might also be related to #160 as that's also `vscode-jsonrpc`.

**Comment by octref** [comment]
Any updates? Still happening to you w/ newest version?

**Comment by jonthegiant** [comment]
Haven't had a chance to test it properly yet. I'll ping you back as soon as I know more.

**Comment by jonthegiant** [comment]
@octref 0.6.4 seemed stable for the past few days. The extension host hasn't crashed.

I did however receive this error for the first time today, I just recently updated to VSCode 1.12:
```
[Error - 2:14:31 PM] Server initialization failed.
  Message: Request initialize failed with message: Cannot read property 'substr' of null
  Code: -32603 
```

**Comment by octref** [comment]
@jonthegiant Were you opening a single file? Might be #160.

Closing this issue as it seems to be fixed.

**Comment by jonthegiant** [comment]
Yep, should have stated that, sorry.

**Comment by octref** [comment]
No worries, I'll fix that this week too.
