### ISSUE TITLE
The Vue Language Server server crashed

### ISSUE THREAD

**Issue by lyn-ho** [octref/vetur#143]
```
/home/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23318
                var symbol = container.locals.get(node.text);
```

```
RangeError: Maximum call stack size exceeded
    at Map.get (native)
    at isNameOfExportsOrModuleExportsAliasDeclaration (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23318:47)
    at isExportsOrModuleExportsOrAlias (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23314:17)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23329:20)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23330:92)
    at isNameOfExportsOrModuleExportsAliasDeclaration (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23322:32)
    at isExportsOrModuleExportsOrAlias (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23314:17)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23329:20)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23330:92)
    at isNameOfExportsOrModuleExportsAliasDeclaration (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23322:32)
    at isExportsOrModuleExportsOrAlias (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23314:17)
[Info  - 10:29:00 AM] Connection to server got closed. Server will restart.
/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23318
                var symbol = container.locals.get(node.text);
                                              ^

RangeError: Maximum call stack size exceeded
    at Map.get (native)
    at isNameOfExportsOrModuleExportsAliasDeclaration (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23318:47)
    at isExportsOrModuleExportsOrAlias (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23314:17)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23329:20)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23330:92)
    at isNameOfExportsOrModuleExportsAliasDeclaration (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23322:32)
    at isExportsOrModuleExportsOrAlias (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23314:17)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23329:20)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23330:92)
    at isNameOfExportsOrModuleExportsAliasDeclaration (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23322:32)
    at isExportsOrModuleExportsOrAlias (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23314:17)
[Info  - 10:29:36 AM] Connection to server got closed. Server will restart.
/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:9401
    function isAssignmentExpression(node, excludeCompoundAssignment) {
                                   ^

RangeError: Maximum call stack size exceeded
    at Object.isAssignmentExpression (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:9401:36)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23330:21)
    at isNameOfExportsOrModuleExportsAliasDeclaration (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23322:32)
    at isExportsOrModuleExportsOrAlias (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23314:17)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23329:20)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23330:92)
    at isNameOfExportsOrModuleExportsAliasDeclaration (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23322:32)
    at isExportsOrModuleExportsOrAlias (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23314:17)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23329:20)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23330:92)
[Info  - 10:30:12 AM] Connection to server got closed. Server will restart.
/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23318
                var symbol = container.locals.get(node.text);
                                              ^

RangeError: Maximum call stack size exceeded
    at Map.get (native)
    at isNameOfExportsOrModuleExportsAliasDeclaration (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23318:47)
    at isExportsOrModuleExportsOrAlias (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23314:17)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23329:20)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23330:92)
    at isNameOfExportsOrModuleExportsAliasDeclaration (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23322:32)
    at isExportsOrModuleExportsOrAlias (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23314:17)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23329:20)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23330:92)
    at isNameOfExportsOrModuleExportsAliasDeclaration (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23322:32)
    at isExportsOrModuleExportsOrAlias (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23314:17)
[Info  - 10:30:50 AM] Connection to server got closed. Server will restart.
/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23318
                var symbol = container.locals.get(node.text);
                                              ^

RangeError: Maximum call stack size exceeded
    at Map.get (native)
    at isNameOfExportsOrModuleExportsAliasDeclaration (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23318:47)
    at isExportsOrModuleExportsOrAlias (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23314:17)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23329:20)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23330:92)
    at isNameOfExportsOrModuleExportsAliasDeclaration (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23322:32)
    at isExportsOrModuleExportsOrAlias (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23314:17)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23329:20)
    at isExportsOrModuleExportsOrAliasOrAssignemnt (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23330:92)
    at isNameOfExportsOrModuleExportsAliasDeclaration (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23322:32)
    at isExportsOrModuleExportsOrAlias (/Users/lyn/.vscode/extensions/octref.vetur-0.6.1/client/server/node_modules/typescript/lib/typescript.js:23314:17)
[Error - 10:31:27 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by minororange** [comment]
+10086

**Comment by qiming-kooboo** [comment]
+10010

**Comment by MoonBottle** [comment]
+10010

**Comment by Deguang** [comment]
+ 10000

**Comment by Deguang** [comment]
+10000

**Comment by BelinChung** [comment]
Until the author fixes these problems, maybe we can use the old version to develop.
`extensions` - `Install from vsix`
[vetur-0.5.6.vsix.zip](https://github.com/octref/vetur/files/951581/vetur-0.5.6.vsix.zip)
