### ISSUE TITLE
After I update 0.6.1 version and submit them to the following error

### ISSUE THREAD

**Issue by musishui** [octref/vetur#144]
C:\Users\Jusfoun\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:10566
            throw new Error("start < 0");
            ^

Error: start < 0
    at createTextSpan (C:\Users\Jusfoun\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:10566:19)
    at Object.createTextSpanFromBounds (C:\Users\Jusfoun\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:10575:16)
    at getErrorSpanForNode (C:\Users\Jusfoun\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:7075:19)
    at createDiagnosticForNodeInSourceFile (C:\Users\Jusfoun\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:6999:20)
    at Object.createDiagnosticForNode (C:\Users\Jusfoun\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:6995:16)
    at C:\Users\Jusfoun\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:21582:58
    at Object.forEach (C:\Users\Jusfoun\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:1423:30)
    at declareSymbol (C:\Users\Jusfoun\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:21581:28)
    at declareModuleMember (C:\Users\Jusfoun\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:21600:28)
    at declareSourceFileMember (C:\Users\Jusfoun\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:22646:19)
    at declareSymbolAndAddToSymbolTableWorker (C:\Users\Jusfoun\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:22596:28)
[Info  - 上午9:37:04] Connection to server got closed. Server will restart.
C:\Users\Jusfoun\.vscode\extensions\octref.vetur-0.6.1\client\server\node_modules\typescript\lib\typescript.js:10566
            throw new Error("start < 0");

**Comment by yulin724** [comment]
mee too

**Comment by aherreraGH** [comment]
ditto... just updated today and the stacktrace is the same as provided above.

**Comment by rhyek** [comment]
Same.

**Comment by lucastheisen** [comment]
This is related to #136, so we need to come up with steps to reproduce...  I'll give it a try...

**Comment by aherreraGH** [comment]
looks like it was resolved in #128 something about importing vue twice.

**Comment by BelinChung** [comment]
Until the author fixes these problems, maybe we can use the old version to develop.
extensions - Install from vsix
[vetur-0.5.6.vsix.zip](https://github.com/octref/vetur/files/953624/vetur-0.5.6.vsix.zip)

**Comment by octref** [comment]
Dup of #128.

Can you try installing 0.6.2 and see if the problem is gone?

**Comment by musishui** [comment]
@aherreraGH Thanks.

According to what you say, my problem is resolved.I'm in. Vue file reference vue module, led to this error.

**Comment by octref** [comment]
Can you try 0.6.2 with `import Vue from 'Vue'`? This should be supported with 0.6.2.
