### ISSUE TITLE
Cannot start debugger server

### ISSUE THREAD

**Issue by jpillora** [octref/vetur#148]
In VS Code "Output" tab, when I select `Vue Language Server`, I see:

```
[0425/164617:ERROR:tcp_listen_socket.cc(76)] Could not bind socket to 127.0.0.1:6005
[0425/164617:ERROR:node_debugger.cc(86)] Cannot start debugger server
/Users/jpillora/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/typescript/lib/typescript.js:23318
                var symbol = container.locals.get(node.text);
                                             ^

TypeError: Cannot read property 'get' of undefined
    at isNameOfExportsOrModuleExportsAliasDeclaration (/Users/jpillora/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/typescript/lib/typescript.js:23318:46)
    at bindStaticPropertyAssignment (/Users/jpillora/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/typescript/lib/typescript.js:23396:17)
    at bindWorker (/Users/jpillora/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/typescript/lib/typescript.js:23079:29)
    at bind (/Users/jpillora/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/typescript/lib/typescript.js:22974:13)
    at visitNode (/Users/jpillora/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/typescript/lib/typescript.js:14662:20)
    at Object.forEachChild (/Users/jpillora/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/typescript/lib/typescript.js:14826:24)
    at bindEachChild (/Users/jpillora/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/typescript/lib/typescript.js:21771:16)
    at bindBinaryExpressionFlow (/Users/jpillora/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/typescript/lib/typescript.js:22416:17)
    at bindChildrenWorker (/Users/jpillora/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/typescript/lib/typescript.js:21831:21)
    at bindChildren (/Users/jpillora/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/typescript/lib/typescript.js:21746:17)
[Info  - 4:47:00 pm] Connection to server got closed. Server will restart.
/Users/jpillora/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/typescript/lib/typescript.js:23318
                var symbol = container.locals.get(node.text);
                                             ^
[Error - 4:49:32 pm] Connection to server got closed. Server will not be restarted.
```

**Comment by jing2si** [comment]
I have the same problem.
### My environment
* vscode version: 1.11.2
* vetur version: 0.6.2
* OS: windows 10
### My repro step
1. I create two folder, then create a empty vue file separately in folder.
2. I drag one folder into vscode, then i create new vscode window(File > New Window).
3. I drag the other folder into new vscode window, then open the vue file, the `Cannot start debugger server` will display.

### Gif repro step
![12](https://cloud.githubusercontent.com/assets/2288824/25376276/259da5cc-29d6-11e7-9efc-8e9bd80db760.gif)

**Comment by icehaunter** [comment]
Same problem, but for file editing in general (#156) and on 0.6.2
