### ISSUE TITLE
Error:  vue packages version mismatch

### ISSUE THREAD

**Issue by BlueGene89** [octref/vetur#149]
Error: 

Vue packages version mismatch:

- vue@2.2.6
- vue-template-compiler@2.2.1

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (C:\Users\Rui\.vscode\extensions\octref.vetur-0.6.2\client\server\node_modules\vue-template-compiler\index.js:8:9)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Rui\.vscode\extensions\octref.vetur-0.6.2\client\server\modes\typescriptMode.js:5:31)
    at Module._compile (module.js:556:32)
[Info  - 下午7:13:02] Connection to server got closed. Server will restart.
C:\Users\Rui\.vscode\extensions\octref.vetur-0.6.2\client\server\node_modules\vue-template-compiler\index.js:8
  throw new Error(
  ^

**Comment by octref** [comment]
Dup of #135.
