### ISSUE TITLE
Request textDocument/definition failed.

### ISSUE THREAD

**Issue by Deguang** [octref/vetur#154]
[Error - 8:46:27 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603 
/Users/***/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46
            this.len = source.length;
                             ^

TypeError: Cannot read property 'length' of undefined
    at new MultiLineStream (/Users/***/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:46:30)
    at Object.createScanner (/Users/***/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/vetur-vls/lib/parser/htmlScanner.js:188:22)
    at Object.getDocumentRegions (/Users/***/.vscode/extensions/octref.vetur-0.6.2/client/server/modes/embeddedSupport.js:9:35)
    at /Users/***/.vscode/extensions/octref.vetur-0.6.2/client/server/modes/languageModes.js:11:125
    at Object.get (/Users/***/.vscode/extensions/octref.vetur-0.6.2/client/server/languageModelCache.js:30:33)
    at /Users/***/.vscode/extensions/octref.vetur-0.6.2/client/server/modes/javascriptMode.js:14:43
    at Object.get (/Users/***/.vscode/extensions/octref.vetur-0.6.2/client/server/languageModelCache.js:30:33)
    at Object.getScriptKind (/Users/***/.vscode/extensions/octref.vetur-0.6.2/client/server/modes/javascriptMode.js:69:33)
    at Object.getScriptKind (/Users/***/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/typescript/lib/typescript.js:70920:31)
    at HostCache.createEntry (/Users/***/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/typescript/lib/typescript.js:84794:36)
[Info  - 10:56:41 AM] Connection to server got closed. Server will restart.
[Error - 11:14:51 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 11:14:51 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 11:20:46 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 11:20:46 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 11:33:11 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 11:33:11 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 11:33:28 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 11:33:28 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 11:33:29 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 11:33:29 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 11:37:42 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603 
[Error - 11:37:42 AM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'length' of undefined
  Code: -32603

**Comment by octref** [comment]
Dup of #134.
