### ISSUE TITLE
The Vue Language Server server crashed 5 times in the last 3 minutes.

### ISSUE THREAD

**Issue by cubodehelio** [octref/vetur#155]
**v0.6.2**

After update to **v0.6.2** the server crashes over and over again no matter what.

```
/home/***/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/typescript/lib/typescript.js:84996
                throw new Error("Could not find file: '" + fileName + "'.");
                ^

Error: Could not find file: '/home/****/github/app/App.vue'.
    at getValidSourceFile (/home/****/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/typescript/lib/typescript.js:84996:23)
    at Object.getSyntacticDiagnostics (/home/****/.vscode/extensions/octref.vetur-0.6.2/client/server/node_modules/typescript/lib/typescript.js:85204:52)
    at Object.doValidation (/home/****/.vscode/extensions/octref.vetur-0.6.2/client/server/modes/javascriptMode.js:129:49)
    at /home/****/.vscode/extensions/octref.vetur-0.6.2/client/server/htmlServerMain.js:142:43
    at Array.forEach (native)
    at validateTextDocument (/home/****/.vscode/extensions/octref.vetur-0.6.2/client/server/htmlServerMain.js:140:59)
    at Timeout._onTimeout (/home/****/.vscode/extensions/octref.vetur-0.6.2/client/server/htmlServerMain.js:134:9)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[Info  - 10:32:48 AM] Connection to server got closed. Server will restart.
```

**Comment by chanon** [comment]
I am having this same crash (since 0.6.1)

**Comment by octref** [comment]
Are you opening vue files outside your workspace?

**Comment by chanon** [comment]
For me, no. It happens with any .vue file in my workspace / project.

**Comment by chanon** [comment]
Not sure if it is related, but here is my tsconfig.json
```
{
	"compilerOptions": {
		"allowJs": true,
		"allowSyntheticDefaultImports": true,
		"module": "es2015",
		"moduleResolution": "node",
		"noImplicitAny": true,
		"experimentalDecorators": true,
		"target": "es5",
		"lib": ["dom", "es5", "es2015.promise"]
	},
	"files": [
		"typings/client.d.ts"
	],
	"include": [
		"src/**/*.ts"
	]
}
```

**Comment by octref** [comment]
Can you
- Try if 0.6.4 works for you
- If not, remove `tsconfig.json` temporarily and see if it still crashes

**Comment by leaves4j** [comment]
same problem with 0.6.4
```
[Info  - 2:45:04 PM] Connection to server got closed. Server will restart.
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: node::Environment::exports_string() const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: v8::Utils::ApiCheck(bool, char const*, char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: v8::internal::Factory::NewByteArray(int, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: v8::internal::TranslationBuffer::CreateByteArray(v8::internal::Factory*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: v8::internal::LCodeGenBase::PopulateDeoptimizationData(v8::internal::Handle<v8::internal::Code>) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 8: v8::internal::LChunk::Codegen() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 9: v8::internal::HCompilationJob::GenerateCodeImpl() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
10: v8::internal::Compiler::FinalizeCompilationJob(v8::internal::CompilationJob*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
11: v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
12: v8::internal::StackGuard::HandleInterrupts() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
13: v8::internal::Runtime_StackGuard(int, v8::internal::Object**, v8::internal::Isolate*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
14: 0x1e2e70206147
15: 0x1e2e7073e0a3
```

**Comment by chanon** [comment]
I get the same style of exception in 0.6.4:
`Could not find file: 'd:\path\to\existing\ComponentThatIAmViewingInVSCodeTab.vue'`

HOWEVER if I delete tsconfig.json, it works! I get working typescript code completion in .vue files (amazing!)

But of course, I need my tsconfig.json ... so it seems like there is a setting in there that is causing this.

**Comment by chanon** [comment]
Update:

I found that this works:
```
{
	"compilerOptions": {
		"allowJs": true,
		"allowSyntheticDefaultImports": true,
		"module": "es2015",
		"moduleResolution": "node",
		"noImplicitAny": true,
		"experimentalDecorators": true,
		"target": "es5",
		"lib": ["dom", "es5", "es2015.promise"]
	}
}
```

But this doesn't. (It will cause the the `Could not find file` exception):
```
{
	"include": [
		"src/**/*.ts"
	]
}
```

So I had an idea and tried this:
```
{
	"compilerOptions": {
		"allowJs": true,
		"allowSyntheticDefaultImports": true,
		"module": "es2015",
		"moduleResolution": "node",
		"noImplicitAny": true,
		"experimentalDecorators": true,
		"target": "es5",
		"lib": ["dom", "es5", "es2015.promise"]
	},
	"files": [
		"typings/client.d.ts"
	],
	"include": [
		"src/**/*.ts",
		"src/**/*.vue"
	]
}
```
(added `"src/**/*.vue"` to `include`)

And it works!
I'm not sure how adding that will affect normal typescript compilation / the webpack build though.

**Comment by chanon** [comment]
It might be good if the .vue files are automatically included somehow.

First impressions after getting the typescript intellisense working in .vue files is that now the only thing missing thing seems to be the 'Cannot find module' errors when importing .vue components

**Comment by cubodehelio** [comment]
I had the same problem even after update to **0.6.4** but seems like @chanon solution above that includes `src/**/*.vue` (`jsconfig.json` in my case) solves the issue.

**Comment by octref** [comment]
> (added "src/**/*.vue" to include)
And it works!
I'm not sure how adding that will affect normal typescript compilation / the webpack build though.

By `src/**/*.ts`, you were saying "only include ts files under /src". `src/**/*` or `src` should work for you.

By default (without `tsconfig.json` or only with `exlucdes` in `tsconfig.json`), then it includes all files in your folder so this bug would not happen.

**Comment by JasinYip** [comment]
I got the error message again! The version of vetur is 0.8.6. The following is the output log:

```
vetur initialized
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::String::NewStringType, int) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 8: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 9: node::Buffer::Utf8Slice(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
10: node::Buffer::Utf8Slice(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
11: v8::internal::StrDup(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
12: v8::internal::compiler::BranchElimination::ControlPathConditions::operator==(v8::internal::compiler::BranchElimination::ControlPathConditions const&) const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
13: v8::internal::compiler::BranchElimination::ControlPathConditions::operator==(v8::internal::compiler::BranchElimination::ControlPathConditions const&) const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
14: 0x1b68034843a7
15: 0x1b680410aedf
[Info  - 4:53:41 PM] Connection to server got closed. Server will restart.
[Error - 4:53:42 PM] Request textDocument/documentHighlight failed.
Error: Connection got disposed.
    at Object.dispose (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/main.js:816:25)
    at Object.dispose (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-languageclient/lib/client.js:66:35)
    at LanguageClient.handleConnectionClosed (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-languageclient/lib/client.js:1071:38)
    at LanguageClient.handleConnectionClosed (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-languageclient/lib/main.js:86:15)
    at closeHandler (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-languageclient/lib/client.js:1059:18)
    at CallbackList.invoke (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/events.js:114:39)
    at Emitter.fire (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/events.js:178:36)
    at closeHandler (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/main.js:212:26)
    at CallbackList.invoke (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/events.js:114:39)
    at Emitter.fire (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/events.js:178:36)
    at IPCMessageReader.AbstractMessageReader.fireClose (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/messageReader.js:126:27)
    at ChildProcess.<anonymous> (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/messageReader.js:244:61)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
vetur initialized
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::String::NewStringType, int) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 8: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 9: node::Buffer::Utf8Slice(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
10: node::Buffer::Utf8Slice(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
11: v8::internal::StrDup(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
12: v8::internal::compiler::BranchElimination::ControlPathConditions::operator==(v8::internal::compiler::BranchElimination::ControlPathConditions const&) const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
13: v8::internal::compiler::BranchElimination::ControlPathConditions::operator==(v8::internal::compiler::BranchElimination::ControlPathConditions const&) const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
14: 0x2f85804043a7
15: 0x2f8580bfb59f
[Info  - 4:54:22 PM] Connection to server got closed. Server will restart.
vetur initialized
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::String::NewStringType, int) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 8: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 9: node::Buffer::Utf8Slice(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
10: node::Buffer::Utf8Slice(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
11: v8::internal::StrDup(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
12: v8::internal::compiler::BranchElimination::ControlPathConditions::operator==(v8::internal::compiler::BranchElimination::ControlPathConditions const&) const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
13: v8::internal::compiler::BranchElimination::ControlPathConditions::operator==(v8::internal::compiler::BranchElimination::ControlPathConditions const&) const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
14: 0x3c2df3b843a7
15: 0x3c2df45ed45f
[Info  - 4:55:01 PM] Connection to server got closed. Server will restart.
vetur initialized
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::String::NewStringType, int) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 8: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 9: node::Buffer::Utf8Slice(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
10: node::Buffer::Utf8Slice(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
11: v8::internal::StrDup(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
12: v8::internal::compiler::BranchElimination::ControlPathConditions::operator==(v8::internal::compiler::BranchElimination::ControlPathConditions const&) const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
13: v8::internal::compiler::BranchElimination::ControlPathConditions::operator==(v8::internal::compiler::BranchElimination::ControlPathConditions const&) const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
14: 0x371d55b043a7
15: 0x371d5674869f
[Info  - 4:55:41 PM] Connection to server got closed. Server will restart.
[Error - 4:55:41 PM] Request textDocument/documentHighlight failed.
Error: Connection got disposed.
    at Object.dispose (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/main.js:816:25)
    at Object.dispose (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-languageclient/lib/client.js:66:35)
    at LanguageClient.handleConnectionClosed (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-languageclient/lib/client.js:1071:38)
    at LanguageClient.handleConnectionClosed (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-languageclient/lib/main.js:86:15)
    at closeHandler (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-languageclient/lib/client.js:1059:18)
    at CallbackList.invoke (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/events.js:114:39)
    at Emitter.fire (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/events.js:178:36)
    at closeHandler (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/main.js:212:26)
    at CallbackList.invoke (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/events.js:114:39)
    at Emitter.fire (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/events.js:178:36)
    at IPCMessageReader.AbstractMessageReader.fireClose (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/messageReader.js:126:27)
    at ChildProcess.<anonymous> (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/messageReader.js:244:61)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
[Error - 4:55:41 PM] Request textDocument/documentHighlight failed.
Error: Connection got disposed.
    at Object.dispose (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/main.js:816:25)
    at Object.dispose (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-languageclient/lib/client.js:66:35)
    at LanguageClient.handleConnectionClosed (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-languageclient/lib/client.js:1071:38)
    at LanguageClient.handleConnectionClosed (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-languageclient/lib/main.js:86:15)
    at closeHandler (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-languageclient/lib/client.js:1059:18)
    at CallbackList.invoke (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/events.js:114:39)
    at Emitter.fire (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/events.js:178:36)
    at closeHandler (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/main.js:212:26)
    at CallbackList.invoke (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/events.js:114:39)
    at Emitter.fire (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/events.js:178:36)
    at IPCMessageReader.AbstractMessageReader.fireClose (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/messageReader.js:126:27)
    at ChildProcess.<anonymous> (/Users/jasinyip/.vscode/extensions/octref.vetur-0.8.6/client/node_modules/vscode-jsonrpc/lib/messageReader.js:244:61)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
vetur initialized
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 2: node::DLOpen(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 3: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 4: v8::internal::FatalProcessOutOfMemory(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 5: v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 6: v8::internal::Factory::NewStringFromUtf8(v8::internal::Vector<char const>, v8::internal::PretenureFlag) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 7: v8::String::NewFromUtf8(v8::Isolate*, char const*, v8::String::NewStringType, int) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 8: node::StringBytes::Encode(v8::Isolate*, char const*, unsigned long, node::encoding) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
 9: node::Buffer::Utf8Slice(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
10: node::Buffer::Utf8Slice(v8::FunctionCallbackInfo<v8::Value> const&) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
11: v8::internal::StrDup(char const*) [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
12: v8::internal::compiler::BranchElimination::ControlPathConditions::operator==(v8::internal::compiler::BranchElimination::ControlPathConditions const&) const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
13: v8::internal::compiler::BranchElimination::ControlPathConditions::operator==(v8::internal::compiler::BranchElimination::ControlPathConditions const&) const [/Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libnode.dylib]
14: 0xa7a692043a7
15: 0xa7a69d7c79f
[Error - 4:56:20 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by yuguangde** [comment]
I got the error message also.Have you slove it? @JasinYip

**Comment by octref** [comment]
@JasinYip @yuguangde Do you have jsconfig / tsconfig? If not try to setup one like so https://vuejs.github.io/vetur/setup.html. Only include frontend code.

**Comment by tsauvajon** [comment]
I have the same problem when opening a project on a remote server (e.g. `\\server-name\path\to\project`).

**Comment by octref** [comment]
@tsauvajon Don't think we can support remote editing yet.

**Comment by stevematdavies** [comment]
Sadly the issue remains in 2019, and despite many users having this issue it appears there is no solution, or the maintainer simply closes the tickets every-time someone opens a bug report.

**Comment by octref** [comment]
Appending to a thread using very outdated version of Vetur when you don't give any error logs or reproducible steps, certainly don't help.

**Comment by stevematdavies** [comment]
So this thread only relates to an  "outdated" version of Vetur? When I clicked on the link from the VSCode plugin to the repo it brings me to this page, after which I search the issues for the problem, and this appears, and its not closed. Are o . suggesting opening a duplicate issue just for the latest version of Vetur, or is this somehow different?

**Comment by octref** [comment]
OP posted with v0.6.2 which is released 2 years ago. Currently version is v0.21.1.

Below is what you see when opening new issue. Please fill them all, most importantly, a reproducible case. See [mcve](https://stackoverflow.com/help/minimal-reproducible-example).

```
- [ ] I have searched through existing issues
- [ ] I have read through [docs](https://vuejs.github.io/vetur)
- [ ] I have read [FAQ](https://github.com/vuejs/vetur/blob/master/docs/FAQ.md)

<!--
  If you are reporting a performance issue, read:
  https://github.com/vuejs/vetur/blob/master/.github/PERF_ISSUE.md
-->

## Info

- Platform: <!-- Win/macOS/Linux -->
- Vetur version:
- VS Code version:

## Problem

<!-- Include error message from Panel -> Output -> Vue Language Server -->
<!-- With screenshot / gif if possible -->

## Reproducible Case

<!--
  Important. Please provide clear steps for reproducing the problem.
  Otherwise we can't help you and your issue might be closed.
  For example, fork https://github.com/octref/veturpack and modify it to reproduce the error,
  then push your changes to GitHub and send us the link.
-->
```

**Comment by stevematdavies** [comment]
Yes thanks, I was also looking this thread to see an implementation of this template, I could cut paste and edit.
