### ISSUE TITLE
0.6.4 The Vue Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by Ringes** [octref/vetur#172]
Still getting this error in 0.6.4. Using Vue and Typescript. This is the error:

Error: Could not find file: 'c:\Users\Maringa\Source\Repos\Nuke\Nuke\src\components\Metadata\MetadataItemDetail.vue'.
    at getValidSourceFile (C:\Users\Maringa\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:84996:23)
    at Object.getSyntacticDiagnostics (C:\Users\Maringa\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:85204:52)
    at Object.doValidation (C:\Users\Maringa\.vscode\extensions\octref.vetur-0.6.4\client\server\modes\javascriptMode.js:131:49)
    at C:\Users\Maringa\.vscode\extensions\octref.vetur-0.6.4\client\server\htmlServerMain.js:142:43
    at Array.forEach (native)
    at validateTextDocument (C:\Users\Maringa\.vscode\extensions\octref.vetur-0.6.4\client\server\htmlServerMain.js:140:59)
    at Timeout._onTimeout (C:\Users\Maringa\.vscode\extensions\octref.vetur-0.6.4\client\server\htmlServerMain.js:134:9)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
[Info  - 09:19:46] Connection to server got closed. Server will restart.
C:\Users\Maringa\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:84996
                throw new Error("Could not find file: '" + fileName + "'.");

Also using:
-vue-class-component
-vue-property-decorator

The component giving the error has two files:
1. MetadataItemDetail.ts

import Vue from "vue";
import Component from "vue-class-component";
import {Prop, Watch} from "vue-property-decorator";

@Component({
    name: "MetadataItemDetail",
})
export default class MetadataItemDetail extends Vue {
  ...
}

2. MetadataItemDetail.vue

<template>
    ...
</template>

<script lang="ts">
import MetadataItemDetail from './MetadataItemDetail.ts'
export default MetadataItemDetail
</script>

<style scoped>

</style>

**Comment by ppasieka** [comment]
try to set 
`
    "include": [
	"src/**/*.ts",
	"src/**/*.vue"
    ]
`
inside your tsconfig.json file

**Comment by Ringes** [comment]
Thanks very much, that has resolved the issue

**Comment by proehlen** [comment]
I started getting the same error after just upgrading to the latest version however I'm not using Typescript so don't have a `tsconfig.json` file.  My project is a standard javascript/node/electron project.  Any ideas what I can do to fix this?

**Comment by Treri** [comment]
same problem. my project do not have a tsconfig or jsconfig. Can this be solved?

version 0.6.9

**Comment by octref** [comment]
@Treri @proehlen Open new issue with clear description of the error log, the file you are having problem with and jsconfig/tsconfig info.

**Comment by GuangChao-Yu** [comment]
same problem my project not have a tsconfig file...how to solved ? help
