### ISSUE TITLE
0.6.4 crashed when single vue component opened

### ISSUE THREAD

**Issue by topul** [octref/vetur#182]
.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:23318
                var symbol = container.locals.get(node.text);
                                             ^

TypeError: Cannot read property 'get' of undefined
    at isNameOfExportsOrModuleExportsAliasDeclaration (C:\Users\kingdee\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:23318:46)
    at bindStaticPropertyAssignment (C:\Users\kingdee\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:23396:17)
    at bindWorker (C:\Users\kingdee\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:23079:29)
    at bind (C:\Users\kingdee\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:22974:13)
    at visitNode (C:\Users\kingdee\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:14662:20)
    at Object.forEachChild (C:\Users\kingdee\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:14725:21)
    at bindEachChild (C:\Users\kingdee\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:21771:16)
    at bindChildrenWorker (C:\Users\kingdee\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:21852:21)
    at bindChildren (C:\Users\kingdee\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:21746:17)
    at bind (C:\Users\kingdee\.vscode\extensions\octref.vetur-0.6.4\client\server\node_modules\typescript\lib\typescript.js:22985:21)
[Info  - 上午10:01:05] Connection to server got closed. Server will restart.

**Comment by topul** [comment]
update to 0.6.5, this problem gone
