### ISSUE TITLE
Could not to format script part in vue.

### ISSUE THREAD

**Issue by zjuwjf** [octref/vetur#186]
It worked in html, css parts, but couldn't  format for the script part in vue.

Any one who has the same problem?

**Comment by zjuwjf** [comment]
now I update vetur to 0.6.7 for Windows
I got errors. 



vetur initialized
C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\node_modules\typescript\lib\typescript.js:85887
                throw new Error("Could not find file: '" + fileName + "'.");
                ^

Error: Could not find file: '/d:/wjs-git/app-weex/src/page/account-history-detail.vue'.
    at getValidSourceFile (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\node_modules\typescript\lib\typescript.js:85887:23)
    at Object.getSyntacticDiagnostics (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\node_modules\typescript\lib\typescript.js:86095:52)
    at Object.doValidation (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\modes\javascriptMode.js:137:49)
    at C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\htmlServerMain.js:107:43
    at Array.forEach (native)
    at validateTextDocument (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\htmlServerMain.js:105:59)
    at Timeout._onTimeout (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\htmlServerMain.js:99:9)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[Info  - 下午12:48:44] Connection to server got closed. Server will restart.
vetur initialized
C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\node_modules\typescript\lib\typescript.js:85887
                throw new Error("Could not find file: '" + fileName + "'.");
                ^

Error: Could not find file: '/d:/wjs-git/app-weex/src/page/account-history-detail.vue'.
    at getValidSourceFile (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\node_modules\typescript\lib\typescript.js:85887:23)
    at Object.getSyntacticDiagnostics (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\node_modules\typescript\lib\typescript.js:86095:52)
    at Object.doValidation (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\modes\javascriptMode.js:137:49)
    at C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\htmlServerMain.js:107:43
    at Array.forEach (native)
    at validateTextDocument (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\htmlServerMain.js:105:59)
    at Timeout._onTimeout (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\htmlServerMain.js:99:9)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[Info  - 下午12:48:50] Connection to server got closed. Server will restart.
vetur initialized
C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\node_modules\typescript\lib\typescript.js:85887
                throw new Error("Could not find file: '" + fileName + "'.");
                ^

Error: Could not find file: '/d:/wjs-git/app-weex/src/page/account-history-detail.vue'.
    at getValidSourceFile (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\node_modules\typescript\lib\typescript.js:85887:23)
    at Object.getSyntacticDiagnostics (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\node_modules\typescript\lib\typescript.js:86095:52)
    at Object.doValidation (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\modes\javascriptMode.js:137:49)
    at C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\htmlServerMain.js:107:43
    at Array.forEach (native)
    at validateTextDocument (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\htmlServerMain.js:105:59)
    at Timeout._onTimeout (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\htmlServerMain.js:99:9)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[Info  - 下午12:48:54] Connection to server got closed. Server will restart.
vetur initialized
C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\node_modules\typescript\lib\typescript.js:85887
                throw new Error("Could not find file: '" + fileName + "'.");
                ^

Error: Could not find file: '/d:/wjs-git/app-weex/src/page/account-history-detail.vue'.
    at getValidSourceFile (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\node_modules\typescript\lib\typescript.js:85887:23)
    at Object.getSyntacticDiagnostics (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\node_modules\typescript\lib\typescript.js:86095:52)
    at Object.doValidation (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\modes\javascriptMode.js:137:49)
    at C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\htmlServerMain.js:107:43
    at Array.forEach (native)
    at validateTextDocument (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\htmlServerMain.js:105:59)
    at Timeout._onTimeout (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\htmlServerMain.js:99:9)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[Info  - 下午12:48:59] Connection to server got closed. Server will restart.
vetur initialized
C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\node_modules\typescript\lib\typescript.js:85887
                throw new Error("Could not find file: '" + fileName + "'.");
                ^

Error: Could not find file: '/d:/wjs-git/app-weex/src/page/account-history-detail.vue'.
    at getValidSourceFile (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\node_modules\typescript\lib\typescript.js:85887:23)
    at Object.getSyntacticDiagnostics (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\node_modules\typescript\lib\typescript.js:86095:52)
    at Object.doValidation (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\modes\javascriptMode.js:137:49)
    at C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\htmlServerMain.js:107:43
    at Array.forEach (native)
    at validateTextDocument (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\htmlServerMain.js:105:59)
    at Timeout._onTimeout (C:\Users\zju_wjf\.vscode\extensions\octref.vetur-0.6.7\client\server\htmlServerMain.js:99:9)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[Error - 下午12:49:03] Connection to server got closed. Server will not be restarted.

**Comment by octref** [comment]
Probably due to language server's crash which should be fixed in 0.6.8. See #183 for details.
