### ISSUE TITLE
vetur 0.6.10 crashing with Maximum call stack size exceed at Object.getSpecialPropertyAssignmentKind

### ISSUE THREAD

**Issue by RyanFDev** [octref/vetur#211]
```
/home/kritical/.vscode/extensions/octref.vetur-0.6.10/client/server/node_modules/typescript/lib/typescript.js:7890
    function getSpecialPropertyAssignmentKind(expression) {
                                             ^

RangeError: Maximum call stack size exceeded
    at Object.getSpecialPropertyAssignmentKind (/home/kritical/.vscode/extensions/octref.vetur-0.6.10/client/server/node_modules/typescript/lib/typescript.js:7890:46)
    at bindWorker (/home/kritical/.vscode/extensions/octref.vetur-0.6.10/client/server/node_modules/typescript/lib/typescript.js:23128:42)
    at bind (/home/kritical/.vscode/extensions/octref.vetur-0.6.10/client/server/node_modules/typescript/lib/typescript.js:23037:13)
    at visitNode (/home/kritical/.vscode/extensions/octref.vetur-0.6.10/client/server/node_modules/typescript/lib/typescript.js:14712:20)
    at Object.forEachChild (/home/kritical/.vscode/extensions/octref.vetur-0.6.10/client/server/node_modules/typescript/lib/typescript.js:14876:24)
    at bindEachChild (/home/kritical/.vscode/extensions/octref.vetur-0.6.10/client/server/node_modules/typescript/lib/typescript.js:21830:16)
    at bindBinaryExpressionFlow (/home/kritical/.vscode/extensions/octref.vetur-0.6.10/client/server/node_modules/typescript/lib/typescript.js:22476:17)
    at bindChildrenWorker (/home/kritical/.vscode/extensions/octref.vetur-0.6.10/client/server/node_modules/typescript/lib/typescript.js:21890:21)
    at bindChildren (/home/kritical/.vscode/extensions/octref.vetur-0.6.10/client/server/node_modules/typescript/lib/typescript.js:21805:17)
    at bind (/home/kritical/.vscode/extensions/octref.vetur-0.6.10/client/server/node_modules/typescript/lib/typescript.js:23048:21)
[Error - 2:27:56 PM] Connection to server got closed. Server will not be restarted.

```

Just started happening within the last 24 hours but I can't figure out what I could have changed to cause it.

I don't have a jsconfig or tsconfig file.

**Comment by octref** [comment]
Sorry, was busy for a few days. Did you solve the problem urself?

**Comment by RyanFDev** [comment]
No but I saw lots of similar related issues so I closed it. Doing the check
in #166 I am injesting 33 files only. not using a tsconfig or jsconfig
file. Running Ubuntu 16.04

Love the extension great work!

**Comment by octref** [comment]
I'm looking into it tonight. Have been busy studying for finals.

**Comment by RyanFDev** [comment]
No buddy I tried to look into it myself but I have a time constraint with
my Curren project so I just am ignoring it for now. If you need more info
let me know.

**Comment by octref** [comment]
Do you mind showing me the active file that you are editing when this problem happens?
