### ISSUE TITLE
vue-language-server crashes

### ISSUE THREAD

**Issue by p-adams** [octref/vetur#258]
I am trying out vetur for the first time and I cannot figure out why the vue-language-server crashes. Here is the output of the error message:

`vetur initialized
/Users/user/.vscode/extensions/octref.vetur-0.8.2/client/node_modules/vue-language-server/dist/modes/template/services/htmlValidation.js:31
    return report.results[0].messages.map(toDiagnostic);`
                            ^

`TypeError: Cannot read property 'messages' of undefined
    at Object.doValidation (/Users/user/.vscode/extensions/octref.vetur-0.8.2/client/node_modules/vue-language-server/dist/modes/template/services/htmlValidation.js:31:29)
    at Object.doValidation (/Users/user/.vscode/extensions/octref.vetur-0.8.2/client/node_modules/vue-language-server/dist/modes/template/index.js:29:37)
    at /Users/user/.vscode/extensions/octref.vetur-0.8.2/client/node_modules/vue-language-server/dist/vueServerMain.js:114:43
    at Array.forEach (native)
    at validateTextDocument (/Users/user/.vscode/extensions/octref.vetur-0.8.2/client/node_modules/vue-language-server/dist/vueServerMain.js:112:59)
    at Timeout._onTimeout (/Users/user/.vscode/extensions/octref.vetur-0.8.2/client/node_modules/vue-language-server/dist/vueServerMain.js:106:9)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
[Info  - 1:20:46 PM] Connection to server got closed. Server will restart.`

It attempts to restart the server five times before giving the final error message:

`[Error - 1:21:00 PM] Connection to server got closed. Server will not be restarted.`

**Comment by octref** [comment]
Sorry about that. Added a fix and will be available in the next release soon.
