### ISSUE TITLE
vetur 崩溃

### ISSUE THREAD

**Issue by zhaozhe0831** [octref/vetur#277]
- Platform: macOS
- Vetur version: 0.8.5
- VSCode version: 1.13.1
- vue-cli version: 2.8.2

## Problem

```
/Users/zhaozhe/.vscode/extensions/octref.vetur-0.8.5/client/node_modules/vue-template-compiler/index.js:8
  throw new Error(
  ^

Error: 

Vue packages version mismatch:

- vue@2.0.0-rc.8
- vue-template-compiler@2.3.4

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

    at Object.<anonymous> (/Users/zhaozhe/.vscode/extensions/octref.vetur-0.8.5/client/node_modules/vue-template-compiler/index.js:8:9)
    at Object.<anonymous> (/Users/zhaozhe/.vscode/extensions/octref.vetur-0.8.5/client/node_modules/vue-template-compiler/index.js:20:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/zhaozhe/.vscode/extensions/octref.vetur-0.8.5/client/node_modules/vue-language-server/dist/modes/script/typescript.js:5:31)
[Info  - 8:23:49 PM] Connection to server got closed. Server will restart.
```

## Reproducible Case

与 #250 的问题相似。
我用 vue-cli 构建了项目，用的是官方的模板 'webpack'。
npm install 之后，打开 *.vue 文件，vetur 崩溃

**Comment by xiguaxigua** [comment]
vue和vue-template-compiler版本需要一致，安装一个与vue版本一致的vue-template-compiler重新打开试试？

**Comment by zhaozhe0831** [comment]
是一致的。


原始邮件
发件人:西瓜notifications@github.com
收件人:octref/veturvetur@noreply.github.com
抄送:阿炳420193833@qq.com; Authorauthor@noreply.github.com
发送时间:2017年6月24日(周六) 23:01
主题:Re: [octref/vetur] vetur 崩溃 (#277)


vue和vue-template-compiler版本需要一致，安装一个与vue版本一致的vue-template-compiler重新打开试试？

**Comment by zhaozhe0831** [comment]
@HerringtonDarkholme 这个问题是什么原因？BUG？还是其他的原因？

**Comment by octref** [comment]
Read #250 and please use English in this repository. Thank you.

**Comment by zhaozhe0831** [comment]
我英语不好真是对不起你了呢。
